---

- name: Install packages
  dnf:
    name:
      - arandr
      - autorandr
      - blueman
      - dmenu
      - dunst
      - feh
      - i3
      - picom
      - polybar
      - xsetroot
    state: latest
