---

- name: Uninstall packages
  dnf:
    name:

      - cheese
      - cups
      - gfbgraph
      - gnome-boxes
      - gnome-calendar
      - gnome-contacts
      - gnome-dictionary
      - gnome-documents
      - gnome-getting-started-docs
      - gnome-initial-setup
      - gnome-maps
      - gnome-online-miners
      - gnome-photos
      - gnome-software
      - gnome-user-docs
      - gnome-user-share
      - gnome-video-effects
      - gnome-weather
      - libreoffice*
      - nano
      - simple-scan
      - totem
      - tracker-miners
      - yelp
    state: absent


