---

- name: Get installed packages
  dnf:  list=installed
  register: dnf_packages
  changed_when: False

- debug:
    var: dnf_packages

- name: Uninstall packages
  dnf:
    name:
      - cheese
      - eog
      - evolution
      - evolution-ews
      - evolution-help
      - fedora-bookmarks
      - fedora-chromium-config
      - firefox
      - gfbgraph
      - gedit
      - gnome-abrt
      - gnome-boxes
      - gnome-backgrounds
      - gnome-calculator
      - gnome-calendar
      - gnome-characters
      - gnome-contacts
      - gnome-color-manager
      - gnome-clocks
      - gnome-dictionary
      - gnome-documents
      - gnome-getting-started-docs
      - gnome-logs
      - gnome-maps
      - gnome-online-miners
      - gnome-photos
      - gnome-remote-desktop
      - gnome-screenshot
      - gnome-software
      - gnome-system-monitor
      - gnome-user-docs
      - gnome-terminal*
      - gnome-themes*
      - gnome-tour
      - gnome-video-effects
      - gnome-weather
      - google-carlito-fonts
      - google-droid-sans-fonts
      - ibus-hangul
      - ibus-kkc
      - ibus-libpinyin
      - ibus-libzhuyin
      - ibus-m17n
      - ibus-typing-booster
      - khmeros-base-fonts
      - libreoffice*
      - libreport
      - nano
      - nano-default-editor
      - problem-reporting
      - rhythmbox
      - sane-airscan
      - simple-scan
      - speech-dispatcher
      - thai-scalable*
      - totem
      - tracker-miners
      - yelp
    state: absent
