---

# openssl passwd -1 {{ nonroot_user }}
- name: Ensure user '{{ nonroot_user }}' exists
  ansible.builtin.user:
    name: '{{ nonroot_user }}'
    password: '$1$Z4Btxtic$OyRxquW2NVLvF4FK1zffl0'
    shell: /bin/bash
    groups: '{{ nonroot_group }},wheel'
    append: yes
